package com.vinhnguyen.watchai.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

/** First run: users are told they're talking to an AI and where their words go (EU AI Act Art. 50, GDPR). */
@Composable
fun NoticeScreen(onAccept: () -> Unit) {
    Column(
        Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(24.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        Text("Before you start", style = MaterialTheme.typography.headlineMedium)
        Text("Buddy answers with AI models. Answers are generated by a machine and can be wrong.")
        Section(
            "On this phone (Gemma)",
            "Runs entirely on your phone. Nothing you ask leaves it. The first time, the app downloads a 2.6 GB model " +
                "file from Hugging Face over Wi-Fi; Hugging Face sees your IP address during the download.",
        )
        Section(
            "ChatGPT (optional, off until you turn it on)",
            "Your questions go straight from this phone to OpenAI under your own ChatGPT account and plan. " +
                "We never see them. OpenAI's own privacy terms and your ChatGPT data settings apply.",
        )
        Section(
            "What we keep",
            "Your ChatGPT sign-in, encrypted with a key that never leaves this phone. Chats are kept in memory " +
                "only and disappear when you close the app. No analytics, no ads. Settings → Delete everything " +
                "removes it all.",
        )
        Button(onClick = onAccept, modifier = Modifier.fillMaxWidth()) { Text("I understand") }
    }
}

@Composable
private fun Section(
    title: String,
    body: String,
) {
    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Text(title, style = MaterialTheme.typography.titleMedium)
        Text(body, style = MaterialTheme.typography.bodyMedium)
    }
}
